### ISSUE TITLE
saving and loading model error

### ISSUE THREAD

**Issue by stellaywu** [josephsdavid/N2D#8]
Thanks for the useful library! 
Trying to use the saving and loading function
`hcluster = n2d.load_n2d('models/har.h5', 'models/hargmm.sav')`
got an error
`RuntimeError: incompatible bytecode version`

The error message is here 
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-47-13d7e71264cb> in <module>()
      9 
     10 n2d_model = n2d.load_n2d(results_path_base+'n2d_kibana_n100_dim100model.h5',
---> 11                          results_path_base+'n2d_kibana_n100_dim100har.sav')

/anaconda3/lib/python3.6/site-packages/n2d/N2D.py in load_n2d(encoder_id, manifold_id)
    430         - manifold_id: where the manifold learner/clusterer is stored
    431     '''
--> 432     man = pickle.load(open(manifold_id, 'rb'))
    433     out = n2d(10, man)
    434     out.encoder = load_model(encoder_id, compile = False)

/anaconda3/lib/python3.6/site-packages/numba/serialize.py in _rebuild_reduction(cls, *args)
     21     Global hook to rebuild a given class from its __reduce__ arguments.
     22     """
---> 23     return cls._rebuild(*args)
     24 
     25 

/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in _rebuild(cls, uuid, func_reduced, locals, targetoptions, impl_kind, can_compile, sigs)
    563         except KeyError:
    564             pass
--> 565         py_func = serialize._rebuild_function(*func_reduced)
    566         self = cls(py_func, locals, targetoptions, impl_kind)
    567         # Make sure this deserialization will be merged with subsequent ones

/anaconda3/lib/python3.6/site-packages/numba/serialize.py in _rebuild_function(code_reduced, globals, name, cell_values)
     89     else:
     90         cells = ()
---> 91     code = _rebuild_code(*code_reduced)
     92     modname = globals['__name__']
     93     try:

/anaconda3/lib/python3.6/site-packages/numba/serialize.py in _rebuild_code(marshal_version, bytecode_magic, marshalled)
    108                            % (marshal.version, marshal_version))
    109     if imp.get_magic() != bytecode_magic:
--> 110         raise RuntimeError("incompatible bytecode version")
    111     return marshal.loads(marshalled)
    112 

RuntimeError: incompatible bytecode version`

Any suggestions? Thanks!

**Comment by josephsdavid** [comment]
Hmm let me take a look into it in about 14 hours, it’s about time I got around to making saving and loading work better! (see #5 )

I believe this is an issue with serializing Numba (which is why UMAP is so fast), so I’ll look into that! 

For the time being (I’ll get back to you on how big of an issue this is tomorrow), you should be able to use the (probably confusing) weight saving with `.fit()`, so at least you don’t need to train an autoencoder forever. As an explanation (and feedback is appreciated), you first do `model.fit(..., weight_id = “models/modelname.h5”)`, and then if you want to reload the weights, the next time you call fit you run `model.fit(...weights = “models/modelname.h5”)`. Here’s an [example](https://github.com/josephsdavid/N2D/blob/5477f1449f5cebb735a283760631740fdb9401db/examples/clean.py#L26) of using this! You’ll still have to run UMAP, but at least you don’t have to wait on the autoencoder repeatedly. 

I’ll get back to you tomorrow on resolving this!

**Comment by stellaywu** [comment]
Thanks for being so quick! 
was trying to use the model.fit with pre-trained h5, took a very long to load the model. Maybe it's because of my memory is almost full, trying to resolve that. 
Good to find out that about the saving function, was confusing at the beginning as .fit looks the same with slight difference in parameter name (weights vs weights_id) . Once I realize it's two functions it's not confusing anymore.

**Comment by josephsdavid** [comment]
So it appears this is a common issue with UMAP, because I am using `pickle.dump(..., ‘wb’)`, which saves as bytecode and has apparently some issues working on different OSes (https://github.com/lmcinnes/umap/issues/312) (https://github.com/lmcinnes/umap/issues/273) I’ll mess around with how N2D saves the manifold learner today/over the weekend so we can get something working, I may ping you in this thread if that’s ok for some testing, as it works fine on my computer :)


Related to the weights and weight id confusion, do you think it would be easier if the parameters were named `save_weights` and `load_weights`?

**Comment by stellaywu** [comment]
Hey @josephsdavid ! Yes renaming to save and load does look clearer! 
I tried loading the h5 with load_weights, it took a long time to load, is it to be expected?
Another question, for the customized clustering methods, when I use default KNN it produce nicely looked clusters on manifold but no clear boundaries among cluster. When switching to hdbscan, it identified lots of points as noise and many small clusters. My question is, is the best practice the same as using hdbscan directly, in terms of tuning the hyperparameters? 
Thanks!

**Comment by josephsdavid** [comment]
Depending on your computer it could take a while, I will check out if there’s any way I can speed things up on the backend, the big bottleneck (I believe) is when the model is moved from working on your CPU to your GPU, which I can hopefully find the optimal way (the other potential bottleneck is running UMAP, which you should be able to identify by all the output it prints out). I’ll see what I can do related to speed!
As far as hdbscan and manifolds within autoencoded embeddings, it’s an area that has never really been researched (in the UMAP docs there are however examples of using UMAP to improve hdbscan results, so I would assume the hyper parameters are similar, but there is potentially more to it than that (also be aware n2d.visualize only shows the first 5000 or so points, so if you want to see *everything* a little more work needs to be done. [here](https://github.com/josephsdavid/N2D/blob/5477f1449f5cebb735a283760631740fdb9401db/n2d/N2D.py#L232) is a link to the plotting code used in N2D (in conjunction with n2d.visualize() to get you started if you want to do more!)
One last suggestion, if you are happy with the autoencoded embedding and manifold from UMAP, and want to just focus on tuning hdbscan, you can save the manifold to a numpy array!
```python
# for looking at your training data
def get_manifold(n2d_obj):
    return n2d_obj.hle

# for new data, if you put your training data as newdata youll get the training manifold
def predict_manifold(n2d_obj, newdata):
    embedding = n2d_obj.encoder.predict(newdata)
    manifold_in_embedding = n2d_obj.manifolder.transform(embedding)
    return manifold_in_embedding

# then you can quickly fiddle with hdbscan parameters without running the other steps
```

This is based on the advanced usage documentation, which I will further document with the coming upgrade (fixing saving!)

**Comment by stellaywu** [comment]
Thanks so much for the detailed response! I will try that looks like a big time saver! Looking forward to the saving updates. For now I am using the model.fit function it  solves my problem so far. will close the issue for now.

**Comment by josephsdavid** [comment]
Great! I will respond here when I figure out these issues with Numba and UMAP/expect an update in the next week or two!

**Comment by konradsemsch** [comment]
Hi @josephsdavid! Is there any update on the `numba` topic? I'm having similar issues when saving and loading umap object within an sklearn pipeline. We got it already working on Windows and MacOS, however, now when we're brining it to production on Ubuntu it's failing again. Not quite sure where to start debugging this. I mentioned my error [here](https://github.com/lmcinnes/umap/issues/473#issuecomment-675340411).
